version: 2

updates:
# Updates for the main branch
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "npm"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 25
    groups:
      npm-dependencies:
        patterns:
          - "*"
